language: node_js
node_js:
  - 10

before_script:
  - npm install

script:
  - npm run build

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "kkiapay-‚*.tgz"
    skip_cleanup: true
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: ["nafiouali@gmail.com"]
    api_key: $NPM_TOKEN
    on:
      tags: true
